server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mailDB?serverTimezone=Asia/Seoul
    username: root
    password: pw123

  mail:
    host: mail.vcinc.co.kr
    port: 25
    username: jnkim@vcinc.co.kr
    password: kjy86441128!
  mvc:
    hiddenmethod:
      filter:
        enabled: true


http:
  auth-token-header:
    name: Authorization
  authToken:
    server1: qwe
    server2: qwer
    server3: qwert




